services:
  assistant:
    image: assitant:v1.0
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CRYPTOGRAPHY_KEY=${CRYPTOGRAPHY_KEY}
      - MASTER_KEY=${MASTER_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./database/data:/assistant/database/data
