name: Develop - Build and Deploy

on:
  push:
    branches: 
      - dev    
    tags:
      - 'dev-v*.*.*'
  pull_request:
    branches:
      - dev

env:
  IMAGE_NAME: assistant-bot
  VPS_WORKING_DIR: /srv/docker/assistant-bot

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Get the date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:dev-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:dev-${{ env.date }}
          secrets: |
            "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
            "CRYPTOGRAPHY_KEY=${{ secrets.CRYPTOGRAPHY_KEY }}"
            "MASTER_KEY=${{ secrets.MASTER_KEY }}"

  deploy:
    needs: build-and-push
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to dev
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ env.VPS_WORKING_DIR }}
            ls -la
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker compose -f docker-compose-dev.yml pull
            docker compose -f docker-compose-dev.yml up -d --force-recreate
